#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Bu kod araç tarafından oluşturuldu.
//     Çalışma Zamanı Sürümü:4.0.30319.42000
//
//     Bu dosyada yapılacak değişiklikler yanlış davranışa neden olabilir ve
//     kod yeniden oluşturulursa kaybolur.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UcakBileti
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="airlines")]
	public partial class airlinesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertflightclass(flightclass instance);
    partial void Updateflightclass(flightclass instance);
    partial void Deleteflightclass(flightclass instance);
    partial void Insertflightprice(flightprice instance);
    partial void Updateflightprice(flightprice instance);
    partial void Deleteflightprice(flightprice instance);
    partial void Insertflying(flying instance);
    partial void Updateflying(flying instance);
    partial void Deleteflying(flying instance);
    partial void Insertlocation(location instance);
    partial void Updatelocation(location instance);
    partial void Deletelocation(location instance);
    partial void Insertpassenger(passenger instance);
    partial void Updatepassenger(passenger instance);
    partial void Deletepassenger(passenger instance);
    partial void Insertplane(plane instance);
    partial void Updateplane(plane instance);
    partial void Deleteplane(plane instance);
    partial void Insertreservation(reservation instance);
    partial void Updatereservation(reservation instance);
    partial void Deletereservation(reservation instance);
    partial void Insertrezervationflying(rezervationflying instance);
    partial void Updaterezervationflying(rezervationflying instance);
    partial void Deleterezervationflying(rezervationflying instance);
    partial void Insertrezervationprice(rezervationprice instance);
    partial void Updaterezervationprice(rezervationprice instance);
    partial void Deleterezervationprice(rezervationprice instance);
    partial void Insertroute(route instance);
    partial void Updateroute(route instance);
    partial void Deleteroute(route instance);
    #endregion
		
		public airlinesDataContext() : 
				base(global::UcakBileti.Properties.Settings.Default.airlinesConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public airlinesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airlinesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airlinesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public airlinesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<flightclass> flightclass
		{
			get
			{
				return this.GetTable<flightclass>();
			}
		}
		
		public System.Data.Linq.Table<flightprice> flightprice
		{
			get
			{
				return this.GetTable<flightprice>();
			}
		}
		
		public System.Data.Linq.Table<flying> flying
		{
			get
			{
				return this.GetTable<flying>();
			}
		}
		
		public System.Data.Linq.Table<location> location
		{
			get
			{
				return this.GetTable<location>();
			}
		}
		
		public System.Data.Linq.Table<passenger> passenger
		{
			get
			{
				return this.GetTable<passenger>();
			}
		}
		
		public System.Data.Linq.Table<plane> plane
		{
			get
			{
				return this.GetTable<plane>();
			}
		}
		
		public System.Data.Linq.Table<reservation> reservation
		{
			get
			{
				return this.GetTable<reservation>();
			}
		}
		
		public System.Data.Linq.Table<rezervationflying> rezervationflying
		{
			get
			{
				return this.GetTable<rezervationflying>();
			}
		}
		
		public System.Data.Linq.Table<rezervationprice> rezervationprice
		{
			get
			{
				return this.GetTable<rezervationprice>();
			}
		}
		
		public System.Data.Linq.Table<route> route
		{
			get
			{
				return this.GetTable<route>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flightclass")]
	public partial class flightclass : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _sınıfkodu;
		
		private string _sınıfadı;
		
		private EntitySet<flightprice> _flightprice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnsınıfkoduChanging(string value);
    partial void OnsınıfkoduChanged();
    partial void OnsınıfadıChanging(string value);
    partial void OnsınıfadıChanged();
    #endregion
		
		public flightclass()
		{
			this._flightprice = new EntitySet<flightprice>(new Action<flightprice>(this.attach_flightprice), new Action<flightprice>(this.detach_flightprice));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sınıfkodu", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string sınıfkodu
		{
			get
			{
				return this._sınıfkodu;
			}
			set
			{
				if ((this._sınıfkodu != value))
				{
					this.OnsınıfkoduChanging(value);
					this.SendPropertyChanging();
					this._sınıfkodu = value;
					this.SendPropertyChanged("sınıfkodu");
					this.OnsınıfkoduChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sınıfadı", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string sınıfadı
		{
			get
			{
				return this._sınıfadı;
			}
			set
			{
				if ((this._sınıfadı != value))
				{
					this.OnsınıfadıChanging(value);
					this.SendPropertyChanging();
					this._sınıfadı = value;
					this.SendPropertyChanged("sınıfadı");
					this.OnsınıfadıChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flightclass_flightprice", Storage="_flightprice", ThisKey="id", OtherKey="ucussınıfıid")]
		public EntitySet<flightprice> flightprice
		{
			get
			{
				return this._flightprice;
			}
			set
			{
				this._flightprice.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flightprice(flightprice entity)
		{
			this.SendPropertyChanging();
			entity.flightclass = this;
		}
		
		private void detach_flightprice(flightprice entity)
		{
			this.SendPropertyChanging();
			entity.flightclass = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flightprice")]
	public partial class flightprice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _ucusid;
		
		private int _ucussınıfıid;
		
		private string _kota;
		
		private string _fiyat;
		
		private string _kullanılankota;
		
		private EntityRef<flightclass> _flightclass;
		
		private EntityRef<flying> _flying;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnucusidChanging(int value);
    partial void OnucusidChanged();
    partial void OnucussınıfıidChanging(int value);
    partial void OnucussınıfıidChanged();
    partial void OnkotaChanging(string value);
    partial void OnkotaChanged();
    partial void OnfiyatChanging(string value);
    partial void OnfiyatChanged();
    partial void OnkullanılankotaChanging(string value);
    partial void OnkullanılankotaChanged();
    #endregion
		
		public flightprice()
		{
			this._flightclass = default(EntityRef<flightclass>);
			this._flying = default(EntityRef<flying>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucusid", DbType="Int NOT NULL")]
		public int ucusid
		{
			get
			{
				return this._ucusid;
			}
			set
			{
				if ((this._ucusid != value))
				{
					if (this._flying.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnucusidChanging(value);
					this.SendPropertyChanging();
					this._ucusid = value;
					this.SendPropertyChanged("ucusid");
					this.OnucusidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucussınıfıid", DbType="Int NOT NULL")]
		public int ucussınıfıid
		{
			get
			{
				return this._ucussınıfıid;
			}
			set
			{
				if ((this._ucussınıfıid != value))
				{
					if (this._flightclass.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnucussınıfıidChanging(value);
					this.SendPropertyChanging();
					this._ucussınıfıid = value;
					this.SendPropertyChanged("ucussınıfıid");
					this.OnucussınıfıidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kota", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string kota
		{
			get
			{
				return this._kota;
			}
			set
			{
				if ((this._kota != value))
				{
					this.OnkotaChanging(value);
					this.SendPropertyChanging();
					this._kota = value;
					this.SendPropertyChanged("kota");
					this.OnkotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullanılankota", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string kullanılankota
		{
			get
			{
				return this._kullanılankota;
			}
			set
			{
				if ((this._kullanılankota != value))
				{
					this.OnkullanılankotaChanging(value);
					this.SendPropertyChanging();
					this._kullanılankota = value;
					this.SendPropertyChanged("kullanılankota");
					this.OnkullanılankotaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flightclass_flightprice", Storage="_flightclass", ThisKey="ucussınıfıid", OtherKey="id", IsForeignKey=true)]
		public flightclass flightclass
		{
			get
			{
				return this._flightclass.Entity;
			}
			set
			{
				flightclass previousValue = this._flightclass.Entity;
				if (((previousValue != value) 
							|| (this._flightclass.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flightclass.Entity = null;
						previousValue.flightprice.Remove(this);
					}
					this._flightclass.Entity = value;
					if ((value != null))
					{
						value.flightprice.Add(this);
						this._ucussınıfıid = value.id;
					}
					else
					{
						this._ucussınıfıid = default(int);
					}
					this.SendPropertyChanged("flightclass");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flying_flightprice", Storage="_flying", ThisKey="ucusid", OtherKey="id", IsForeignKey=true)]
		public flying flying
		{
			get
			{
				return this._flying.Entity;
			}
			set
			{
				flying previousValue = this._flying.Entity;
				if (((previousValue != value) 
							|| (this._flying.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flying.Entity = null;
						previousValue.flightprice.Remove(this);
					}
					this._flying.Entity = value;
					if ((value != null))
					{
						value.flightprice.Add(this);
						this._ucusid = value.id;
					}
					else
					{
						this._ucusid = default(int);
					}
					this.SendPropertyChanged("flying");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.flying")]
	public partial class flying : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _rotationid;
		
		private System.DateTime _ktarih;
		
		private System.DateTime _vtarih;
		
		private int _planeid;
		
		private EntitySet<flightprice> _flightprice;
		
		private EntitySet<rezervationflying> _rezervationflying;
		
		private EntityRef<plane> _plane;
		
		private EntityRef<route> _route;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrotationidChanging(int value);
    partial void OnrotationidChanged();
    partial void OnktarihChanging(System.DateTime value);
    partial void OnktarihChanged();
    partial void OnvtarihChanging(System.DateTime value);
    partial void OnvtarihChanged();
    partial void OnplaneidChanging(int value);
    partial void OnplaneidChanged();
    #endregion
		
		public flying()
		{
			this._flightprice = new EntitySet<flightprice>(new Action<flightprice>(this.attach_flightprice), new Action<flightprice>(this.detach_flightprice));
			this._rezervationflying = new EntitySet<rezervationflying>(new Action<rezervationflying>(this.attach_rezervationflying), new Action<rezervationflying>(this.detach_rezervationflying));
			this._plane = default(EntityRef<plane>);
			this._route = default(EntityRef<route>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rotationid", DbType="Int NOT NULL")]
		public int rotationid
		{
			get
			{
				return this._rotationid;
			}
			set
			{
				if ((this._rotationid != value))
				{
					if (this._route.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrotationidChanging(value);
					this.SendPropertyChanging();
					this._rotationid = value;
					this.SendPropertyChanged("rotationid");
					this.OnrotationidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ktarih", DbType="Date NOT NULL")]
		public System.DateTime ktarih
		{
			get
			{
				return this._ktarih;
			}
			set
			{
				if ((this._ktarih != value))
				{
					this.OnktarihChanging(value);
					this.SendPropertyChanging();
					this._ktarih = value;
					this.SendPropertyChanged("ktarih");
					this.OnktarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vtarih", DbType="Date NOT NULL")]
		public System.DateTime vtarih
		{
			get
			{
				return this._vtarih;
			}
			set
			{
				if ((this._vtarih != value))
				{
					this.OnvtarihChanging(value);
					this.SendPropertyChanging();
					this._vtarih = value;
					this.SendPropertyChanged("vtarih");
					this.OnvtarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_planeid", DbType="Int NOT NULL")]
		public int planeid
		{
			get
			{
				return this._planeid;
			}
			set
			{
				if ((this._planeid != value))
				{
					if (this._plane.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnplaneidChanging(value);
					this.SendPropertyChanging();
					this._planeid = value;
					this.SendPropertyChanged("planeid");
					this.OnplaneidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flying_flightprice", Storage="_flightprice", ThisKey="id", OtherKey="ucusid")]
		public EntitySet<flightprice> flightprice
		{
			get
			{
				return this._flightprice;
			}
			set
			{
				this._flightprice.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flying_rezervationflying", Storage="_rezervationflying", ThisKey="id", OtherKey="ucusid")]
		public EntitySet<rezervationflying> rezervationflying
		{
			get
			{
				return this._rezervationflying;
			}
			set
			{
				this._rezervationflying.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="plane_flying", Storage="_plane", ThisKey="planeid", OtherKey="id", IsForeignKey=true)]
		public plane plane
		{
			get
			{
				return this._plane.Entity;
			}
			set
			{
				plane previousValue = this._plane.Entity;
				if (((previousValue != value) 
							|| (this._plane.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._plane.Entity = null;
						previousValue.flying.Remove(this);
					}
					this._plane.Entity = value;
					if ((value != null))
					{
						value.flying.Add(this);
						this._planeid = value.id;
					}
					else
					{
						this._planeid = default(int);
					}
					this.SendPropertyChanged("plane");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="route_flying", Storage="_route", ThisKey="rotationid", OtherKey="id", IsForeignKey=true)]
		public route route
		{
			get
			{
				return this._route.Entity;
			}
			set
			{
				route previousValue = this._route.Entity;
				if (((previousValue != value) 
							|| (this._route.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._route.Entity = null;
						previousValue.flying.Remove(this);
					}
					this._route.Entity = value;
					if ((value != null))
					{
						value.flying.Add(this);
						this._rotationid = value.id;
					}
					else
					{
						this._rotationid = default(int);
					}
					this.SendPropertyChanged("route");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flightprice(flightprice entity)
		{
			this.SendPropertyChanging();
			entity.flying = this;
		}
		
		private void detach_flightprice(flightprice entity)
		{
			this.SendPropertyChanging();
			entity.flying = null;
		}
		
		private void attach_rezervationflying(rezervationflying entity)
		{
			this.SendPropertyChanging();
			entity.flying = this;
		}
		
		private void detach_rezervationflying(rezervationflying entity)
		{
			this.SendPropertyChanging();
			entity.flying = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.location")]
	public partial class location : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _lid;
		
		private string _lname;
		
		private string _lcode;
		
		private EntitySet<route> _route;
		
		private EntitySet<route> _route1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnlidChanging(int value);
    partial void OnlidChanged();
    partial void OnlnameChanging(string value);
    partial void OnlnameChanged();
    partial void OnlcodeChanging(string value);
    partial void OnlcodeChanged();
    #endregion
		
		public location()
		{
			this._route = new EntitySet<route>(new Action<route>(this.attach_route), new Action<route>(this.detach_route));
			this._route1 = new EntitySet<route>(new Action<route>(this.attach_route1), new Action<route>(this.detach_route1));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lid", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int lid
		{
			get
			{
				return this._lid;
			}
			set
			{
				if ((this._lid != value))
				{
					this.OnlidChanging(value);
					this.SendPropertyChanging();
					this._lid = value;
					this.SendPropertyChanged("lid");
					this.OnlidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lname", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string lname
		{
			get
			{
				return this._lname;
			}
			set
			{
				if ((this._lname != value))
				{
					this.OnlnameChanging(value);
					this.SendPropertyChanging();
					this._lname = value;
					this.SendPropertyChanged("lname");
					this.OnlnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_lcode", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string lcode
		{
			get
			{
				return this._lcode;
			}
			set
			{
				if ((this._lcode != value))
				{
					this.OnlcodeChanging(value);
					this.SendPropertyChanging();
					this._lcode = value;
					this.SendPropertyChanged("lcode");
					this.OnlcodeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="location_route", Storage="_route", ThisKey="lid", OtherKey="kid")]
		public EntitySet<route> route
		{
			get
			{
				return this._route;
			}
			set
			{
				this._route.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="location_route1", Storage="_route1", ThisKey="lid", OtherKey="vid")]
		public EntitySet<route> route1
		{
			get
			{
				return this._route1;
			}
			set
			{
				this._route1.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_route(route entity)
		{
			this.SendPropertyChanging();
			entity.location = this;
		}
		
		private void detach_route(route entity)
		{
			this.SendPropertyChanging();
			entity.location = null;
		}
		
		private void attach_route1(route entity)
		{
			this.SendPropertyChanging();
			entity.location1 = this;
		}
		
		private void detach_route1(route entity)
		{
			this.SendPropertyChanging();
			entity.location1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.passenger")]
	public partial class passenger : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _rezid;
		
		private string _pname;
		
		private string _plastname;
		
		private System.DateTime _pdogumtarihi;
		
		private EntityRef<reservation> _reservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrezidChanging(int value);
    partial void OnrezidChanged();
    partial void OnpnameChanging(string value);
    partial void OnpnameChanged();
    partial void OnplastnameChanging(string value);
    partial void OnplastnameChanged();
    partial void OnpdogumtarihiChanging(System.DateTime value);
    partial void OnpdogumtarihiChanged();
    #endregion
		
		public passenger()
		{
			this._reservation = default(EntityRef<reservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezid", DbType="Int NOT NULL")]
		public int rezid
		{
			get
			{
				return this._rezid;
			}
			set
			{
				if ((this._rezid != value))
				{
					if (this._reservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrezidChanging(value);
					this.SendPropertyChanging();
					this._rezid = value;
					this.SendPropertyChanged("rezid");
					this.OnrezidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pname", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string pname
		{
			get
			{
				return this._pname;
			}
			set
			{
				if ((this._pname != value))
				{
					this.OnpnameChanging(value);
					this.SendPropertyChanging();
					this._pname = value;
					this.SendPropertyChanged("pname");
					this.OnpnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_plastname", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string plastname
		{
			get
			{
				return this._plastname;
			}
			set
			{
				if ((this._plastname != value))
				{
					this.OnplastnameChanging(value);
					this.SendPropertyChanging();
					this._plastname = value;
					this.SendPropertyChanged("plastname");
					this.OnplastnameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pdogumtarihi", DbType="Date NOT NULL")]
		public System.DateTime pdogumtarihi
		{
			get
			{
				return this._pdogumtarihi;
			}
			set
			{
				if ((this._pdogumtarihi != value))
				{
					this.OnpdogumtarihiChanging(value);
					this.SendPropertyChanging();
					this._pdogumtarihi = value;
					this.SendPropertyChanged("pdogumtarihi");
					this.OnpdogumtarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reservation_passenger", Storage="_reservation", ThisKey="rezid", OtherKey="id", IsForeignKey=true)]
		public reservation reservation
		{
			get
			{
				return this._reservation.Entity;
			}
			set
			{
				reservation previousValue = this._reservation.Entity;
				if (((previousValue != value) 
							|| (this._reservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reservation.Entity = null;
						previousValue.passenger.Remove(this);
					}
					this._reservation.Entity = value;
					if ((value != null))
					{
						value.passenger.Add(this);
						this._rezid = value.id;
					}
					else
					{
						this._rezid = default(int);
					}
					this.SendPropertyChanged("reservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.plane")]
	public partial class plane : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _no;
		
		private string _ad;
		
		private EntitySet<flying> _flying;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnnoChanging(int value);
    partial void OnnoChanged();
    partial void OnadChanging(string value);
    partial void OnadChanged();
    #endregion
		
		public plane()
		{
			this._flying = new EntitySet<flying>(new Action<flying>(this.attach_flying), new Action<flying>(this.detach_flying));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_no", DbType="Int NOT NULL")]
		public int no
		{
			get
			{
				return this._no;
			}
			set
			{
				if ((this._no != value))
				{
					this.OnnoChanging(value);
					this.SendPropertyChanging();
					this._no = value;
					this.SendPropertyChanged("no");
					this.OnnoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ad", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ad
		{
			get
			{
				return this._ad;
			}
			set
			{
				if ((this._ad != value))
				{
					this.OnadChanging(value);
					this.SendPropertyChanging();
					this._ad = value;
					this.SendPropertyChanged("ad");
					this.OnadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="plane_flying", Storage="_flying", ThisKey="id", OtherKey="planeid")]
		public EntitySet<flying> flying
		{
			get
			{
				return this._flying;
			}
			set
			{
				this._flying.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flying(flying entity)
		{
			this.SendPropertyChanging();
			entity.plane = this;
		}
		
		private void detach_flying(flying entity)
		{
			this.SendPropertyChanging();
			entity.plane = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.reservation")]
	public partial class reservation : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _rezno;
		
		private System.DateTime _reztarihi;
		
		private string _rezdurumu;
		
		private EntitySet<passenger> _passenger;
		
		private EntitySet<rezervationflying> _rezervationflying;
		
		private EntitySet<rezervationprice> _rezervationprice;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnreznoChanging(int value);
    partial void OnreznoChanged();
    partial void OnreztarihiChanging(System.DateTime value);
    partial void OnreztarihiChanged();
    partial void OnrezdurumuChanging(string value);
    partial void OnrezdurumuChanged();
    #endregion
		
		public reservation()
		{
			this._passenger = new EntitySet<passenger>(new Action<passenger>(this.attach_passenger), new Action<passenger>(this.detach_passenger));
			this._rezervationflying = new EntitySet<rezervationflying>(new Action<rezervationflying>(this.attach_rezervationflying), new Action<rezervationflying>(this.detach_rezervationflying));
			this._rezervationprice = new EntitySet<rezervationprice>(new Action<rezervationprice>(this.attach_rezervationprice), new Action<rezervationprice>(this.detach_rezervationprice));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezno", DbType="Int NOT NULL")]
		public int rezno
		{
			get
			{
				return this._rezno;
			}
			set
			{
				if ((this._rezno != value))
				{
					this.OnreznoChanging(value);
					this.SendPropertyChanging();
					this._rezno = value;
					this.SendPropertyChanged("rezno");
					this.OnreznoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_reztarihi", DbType="Date NOT NULL")]
		public System.DateTime reztarihi
		{
			get
			{
				return this._reztarihi;
			}
			set
			{
				if ((this._reztarihi != value))
				{
					this.OnreztarihiChanging(value);
					this.SendPropertyChanging();
					this._reztarihi = value;
					this.SendPropertyChanged("reztarihi");
					this.OnreztarihiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezdurumu", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string rezdurumu
		{
			get
			{
				return this._rezdurumu;
			}
			set
			{
				if ((this._rezdurumu != value))
				{
					this.OnrezdurumuChanging(value);
					this.SendPropertyChanging();
					this._rezdurumu = value;
					this.SendPropertyChanged("rezdurumu");
					this.OnrezdurumuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reservation_passenger", Storage="_passenger", ThisKey="id", OtherKey="rezid")]
		public EntitySet<passenger> passenger
		{
			get
			{
				return this._passenger;
			}
			set
			{
				this._passenger.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reservation_rezervationflying", Storage="_rezervationflying", ThisKey="id", OtherKey="rezid")]
		public EntitySet<rezervationflying> rezervationflying
		{
			get
			{
				return this._rezervationflying;
			}
			set
			{
				this._rezervationflying.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reservation_rezervationprice", Storage="_rezervationprice", ThisKey="id", OtherKey="rezervationid")]
		public EntitySet<rezervationprice> rezervationprice
		{
			get
			{
				return this._rezervationprice;
			}
			set
			{
				this._rezervationprice.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_passenger(passenger entity)
		{
			this.SendPropertyChanging();
			entity.reservation = this;
		}
		
		private void detach_passenger(passenger entity)
		{
			this.SendPropertyChanging();
			entity.reservation = null;
		}
		
		private void attach_rezervationflying(rezervationflying entity)
		{
			this.SendPropertyChanging();
			entity.reservation = this;
		}
		
		private void detach_rezervationflying(rezervationflying entity)
		{
			this.SendPropertyChanging();
			entity.reservation = null;
		}
		
		private void attach_rezervationprice(rezervationprice entity)
		{
			this.SendPropertyChanging();
			entity.reservation = this;
		}
		
		private void detach_rezervationprice(rezervationprice entity)
		{
			this.SendPropertyChanging();
			entity.reservation = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rezervationflying")]
	public partial class rezervationflying : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _rezid;
		
		private int _ucusid;
		
		private string _durum;
		
		private EntityRef<flying> _flying;
		
		private EntityRef<reservation> _reservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrezidChanging(int value);
    partial void OnrezidChanged();
    partial void OnucusidChanging(int value);
    partial void OnucusidChanged();
    partial void OndurumChanging(string value);
    partial void OndurumChanged();
    #endregion
		
		public rezervationflying()
		{
			this._flying = default(EntityRef<flying>);
			this._reservation = default(EntityRef<reservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezid", DbType="Int NOT NULL")]
		public int rezid
		{
			get
			{
				return this._rezid;
			}
			set
			{
				if ((this._rezid != value))
				{
					if (this._reservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrezidChanging(value);
					this.SendPropertyChanging();
					this._rezid = value;
					this.SendPropertyChanged("rezid");
					this.OnrezidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ucusid", DbType="Int NOT NULL")]
		public int ucusid
		{
			get
			{
				return this._ucusid;
			}
			set
			{
				if ((this._ucusid != value))
				{
					if (this._flying.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnucusidChanging(value);
					this.SendPropertyChanging();
					this._ucusid = value;
					this.SendPropertyChanged("ucusid");
					this.OnucusidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_durum", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string durum
		{
			get
			{
				return this._durum;
			}
			set
			{
				if ((this._durum != value))
				{
					this.OndurumChanging(value);
					this.SendPropertyChanging();
					this._durum = value;
					this.SendPropertyChanged("durum");
					this.OndurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="flying_rezervationflying", Storage="_flying", ThisKey="ucusid", OtherKey="id", IsForeignKey=true)]
		public flying flying
		{
			get
			{
				return this._flying.Entity;
			}
			set
			{
				flying previousValue = this._flying.Entity;
				if (((previousValue != value) 
							|| (this._flying.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._flying.Entity = null;
						previousValue.rezervationflying.Remove(this);
					}
					this._flying.Entity = value;
					if ((value != null))
					{
						value.rezervationflying.Add(this);
						this._ucusid = value.id;
					}
					else
					{
						this._ucusid = default(int);
					}
					this.SendPropertyChanged("flying");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reservation_rezervationflying", Storage="_reservation", ThisKey="rezid", OtherKey="id", IsForeignKey=true)]
		public reservation reservation
		{
			get
			{
				return this._reservation.Entity;
			}
			set
			{
				reservation previousValue = this._reservation.Entity;
				if (((previousValue != value) 
							|| (this._reservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reservation.Entity = null;
						previousValue.rezervationflying.Remove(this);
					}
					this._reservation.Entity = value;
					if ((value != null))
					{
						value.rezervationflying.Add(this);
						this._rezid = value.id;
					}
					else
					{
						this._rezid = default(int);
					}
					this.SendPropertyChanged("reservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.rezervationprice")]
	public partial class rezervationprice : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _rezervationid;
		
		private int _fiyat;
		
		private EntityRef<reservation> _reservation;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnrezervationidChanging(int value);
    partial void OnrezervationidChanged();
    partial void OnfiyatChanging(int value);
    partial void OnfiyatChanged();
    #endregion
		
		public rezervationprice()
		{
			this._reservation = default(EntityRef<reservation>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_rezervationid", DbType="Int NOT NULL")]
		public int rezervationid
		{
			get
			{
				return this._rezervationid;
			}
			set
			{
				if ((this._rezervationid != value))
				{
					if (this._reservation.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnrezervationidChanging(value);
					this.SendPropertyChanging();
					this._rezervationid = value;
					this.SendPropertyChanged("rezervationid");
					this.OnrezervationidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Int NOT NULL")]
		public int fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="reservation_rezervationprice", Storage="_reservation", ThisKey="rezervationid", OtherKey="id", IsForeignKey=true)]
		public reservation reservation
		{
			get
			{
				return this._reservation.Entity;
			}
			set
			{
				reservation previousValue = this._reservation.Entity;
				if (((previousValue != value) 
							|| (this._reservation.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._reservation.Entity = null;
						previousValue.rezervationprice.Remove(this);
					}
					this._reservation.Entity = value;
					if ((value != null))
					{
						value.rezervationprice.Add(this);
						this._rezervationid = value.id;
					}
					else
					{
						this._rezervationid = default(int);
					}
					this.SendPropertyChanged("reservation");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.route")]
	public partial class route : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private int _kid;
		
		private int _vid;
		
		private EntitySet<flying> _flying;
		
		private EntityRef<location> _location;
		
		private EntityRef<location> _location1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnkidChanging(int value);
    partial void OnkidChanged();
    partial void OnvidChanging(int value);
    partial void OnvidChanged();
    #endregion
		
		public route()
		{
			this._flying = new EntitySet<flying>(new Action<flying>(this.attach_flying), new Action<flying>(this.detach_flying));
			this._location = default(EntityRef<location>);
			this._location1 = default(EntityRef<location>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kid", DbType="Int NOT NULL")]
		public int kid
		{
			get
			{
				return this._kid;
			}
			set
			{
				if ((this._kid != value))
				{
					if (this._location.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkidChanging(value);
					this.SendPropertyChanging();
					this._kid = value;
					this.SendPropertyChanged("kid");
					this.OnkidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vid", DbType="Int NOT NULL")]
		public int vid
		{
			get
			{
				return this._vid;
			}
			set
			{
				if ((this._vid != value))
				{
					if (this._location1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnvidChanging(value);
					this.SendPropertyChanging();
					this._vid = value;
					this.SendPropertyChanged("vid");
					this.OnvidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="route_flying", Storage="_flying", ThisKey="id", OtherKey="rotationid")]
		public EntitySet<flying> flying
		{
			get
			{
				return this._flying;
			}
			set
			{
				this._flying.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="location_route", Storage="_location", ThisKey="kid", OtherKey="lid", IsForeignKey=true)]
		public location location
		{
			get
			{
				return this._location.Entity;
			}
			set
			{
				location previousValue = this._location.Entity;
				if (((previousValue != value) 
							|| (this._location.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._location.Entity = null;
						previousValue.route.Remove(this);
					}
					this._location.Entity = value;
					if ((value != null))
					{
						value.route.Add(this);
						this._kid = value.lid;
					}
					else
					{
						this._kid = default(int);
					}
					this.SendPropertyChanged("location");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="location_route1", Storage="_location1", ThisKey="vid", OtherKey="lid", IsForeignKey=true)]
		public location location1
		{
			get
			{
				return this._location1.Entity;
			}
			set
			{
				location previousValue = this._location1.Entity;
				if (((previousValue != value) 
							|| (this._location1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._location1.Entity = null;
						previousValue.route1.Remove(this);
					}
					this._location1.Entity = value;
					if ((value != null))
					{
						value.route1.Add(this);
						this._vid = value.lid;
					}
					else
					{
						this._vid = default(int);
					}
					this.SendPropertyChanged("location1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_flying(flying entity)
		{
			this.SendPropertyChanging();
			entity.route = this;
		}
		
		private void detach_flying(flying entity)
		{
			this.SendPropertyChanging();
			entity.route = null;
		}
	}
}
#pragma warning restore 1591
